apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: gscjr/order-service:20250310002037
          ports:
            - containerPort: 8080
          env:
            - name: DB_CONN_STRING
              value: "postgres://postgres:postgres@postgres-svc:5432/mydb?sslmode=disable"
            - name: REDIS_ADDR
              value: "redis-svc:6379"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq-svc:5672/"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
  namespace: ecommerce
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
