apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: gscjr/payment-service:20250310001425
          env:
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq-svc:5672/"
